alias check-service="/etc/sam/bin/check-services"
alias stop-service="/etc/sam/bin/stop-service"
alias start-service="/etc/sam/bin/start-service"
alias backup="/etc/sam/bin/postgis-backup"
alias restore="/etc/sam/bin/postgis-restore"
alias logs="/etc/sam/bin/logs"
