- name: Wait until the python is present (file /usr/bin/python is present) before continuing
  wait_for:
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    path: /usr/bin/python
    timeout: 5

- name: Check if the deployment-phase.txt file exist
  stat:
    path: "{{sam_path}}/deployment-phase.txt"
  register: deployment_phase_file

- name: If the deployment-phase.txt file exist, deployment phase 01 run it's not needed
  meta:
    end_play
  when: deployment_phase_file.stat.exists

